name: Análise Estática (SAST)

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instalar dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Executar SAST
        run: bandit -r . -f custom
  appscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instalar dependências e executar aplicação
        run: |
          pip install -r requirements.txt 
          nohup python3 app.py &
          sleep 5 # Espera servidor flask inicializar
      - name: HCL AppScan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.7
        with:
          baseurl: "http://cloud.appscan.com"
          target: "http://localhost:5000"
          asoc_key: ${{ secrets.APPSCAN_API_KEYID }} 
          asoc_secret: ${{ secrets.APPSCAN_API_SECRET }} 
          application_id: 5ea30201-13da-4104-ac5d-24e493ca1fd5